services:
- type: web
  plan: starter
  name: rabbitmq
  runtime: image
  image:
    url: rabbitmq:3-management
  dockerCommand: docker-endpoint.sh printf '%s' "${RABBITMQ_ERLANG_COOKIE" > /var/lib/rabbitmq/.erlang.cookie && chmod 0400 /var/lib/rabbitmq/.erlang.cookie && chown rabbitmq /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    value: "Rabbitmq123"
  - key: RABBITMQ_DEFAULT_USER
    value: "rabbitmq"
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: True
    # Used for Mmanagement UI is launched as Web sercive
  - key: PORT
    value: 15672
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq/mnesia
    sizeGB: 10
