services:
- type: web
  name: rabbitmq
  runtime: image
  image:
    url: rabbitmq:3-management
  plan: starter
  envVars:
  - key: RABBITMQ_DEFAULT_USER
    value: "rabbitmq"
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: True
    # Used for Mmanagement UI is launched as Web sercive
  - key: PORT
    value: 15672
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq/mnesia
    sizeGB: 10
