services:
- type: web
  name: rabbitmq
  runtime: docker
  plan: starter
  dockerContext: ./
  dockerfilePath: ./Dockerfile
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    value: "rabbitmqcookie123"
  - key: RABBITMQ_USER
    value: "rabbitmq"
  - key: RABBITMQ_PASS
    generateValue: True
  - key: PORT
    value: 15672
  - key: RABBITMQ_PORT
    value: 5672
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq/mnesia
    sizeGB: 10
